---
groups:
  - name: certify-azure
    jobs:
      - bats-centos
      - bats-ubuntu
      - test-upgrade
      - certify-centos
      - certify-ubuntu

shared:
  - &prepare-director
    task: prepare-director
    file: pipelines/shared/tasks/prepare-director.yml
    params: &prepare-director-params
      BOSH_CLIENT_SECRET: {{bosh_client_secret}}
      INFRASTRUCTURE:     azure
      DIRECTOR_VARS_FILE: {{azure_director_vars_file}}
      OPTIONAL_OPS_FILE: |
        -o bosh-deployment/azure/custom-environment.yml
        -o bosh-deployment/external-ip-with-registry-not-recommended.yml

  - &deploy-director
    task: deploy-director
    file: pipelines/shared/tasks/deploy-director.yml

  - &prepare-bats
    task: prepare-bats
    file: pipelines/shared/tasks/prepare-bats.yml
    params: &prepare-bats-params
      INFRASTRUCTURE:     azure
      BOSH_CLIENT_SECRET: {{bosh_client_secret}}
      BAT_VCAP_PASSWORD:  {{bat_vcap_password}}

  - &run-bats
    task: run-bats
    file: pipelines/shared/tasks/run-bats.yml

  - &teardown
    task: teardown
    file: pipelines/shared/tasks/teardown.yml
    params:
      DEPLOYMENT_NAME: certification

  - &create-environment
    put: environment
    params:
      delete_on_failure: true
      generate_random_name: true
      terraform_source: pipelines/azure/assets/terraform

  - &destroy-environment
    put: environment
    params:
      action: destroy
      env_name_file: environment/name
      terraform_source: pipelines/azure/assets/terraform
    get_params:
      action: destroy

jobs:
  - name: bats-centos
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,    trigger: true}
        - {get: cpi-release,     trigger: true}
        - {get: stemcell,        trigger: true, resource: centos-stemcell}
        - {get: after-midnight,  trigger: true}
        - {get: pipelines,       trigger: false}
        - {get: bosh-cli,        trigger: false}
        - {get: bats,            trigger: false}
        - {get: bosh-deployment, trigger: false}
      - <<: *create-environment
      - <<: *prepare-director
      - do:
          - <<: *deploy-director
          - <<: *prepare-bats
            params:
              <<: *prepare-bats-params
              STEMCELL_NAME: bosh-azure-hyperv-centos-7-go_agent
          - <<: *run-bats
        ensure:
          do:
            - <<: *teardown
            - <<: *destroy-environment

  - name: bats-ubuntu
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,    trigger: true}
        - {get: cpi-release,     trigger: true}
        - {get: stemcell,        trigger: true, resource: ubuntu-stemcell}
        - {get: after-midnight,  trigger: true}
        - {get: pipelines,       trigger: false}
        - {get: bosh-cli,        trigger: false}
        - {get: bats,            trigger: false}
        - {get: bosh-deployment, trigger: false}
      - <<: *create-environment
      - <<: *prepare-director
      - do:
          - <<: *deploy-director
          - <<: *prepare-bats
            params:
              <<: *prepare-bats-params
              STEMCELL_NAME: bosh-azure-hyperv-ubuntu-trusty-go_agent
          - <<: *run-bats
        ensure:
          do:
            - <<: *teardown
            - <<: *destroy-environment

  - name: test-upgrade
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,     trigger: true}
        - {get: cpi-release,      trigger: true}
        - {get: stemcell,         trigger: true, resource: ubuntu-stemcell}
        - {get: after-midnight,   trigger: true}
        - {get: pipelines,        trigger: false}
        - {get: bosh-cli,         trigger: false}
        - {get: centos-stemcell,  trigger: false} # pass-through
        - {get: old-stemcell,     trigger: false, version: {version: "3363.14"}}
        - {get: old-bosh-release, trigger: false, version: {version: "255.4"}, resource: bosh-release}
        - {get: old-cpi-release,  trigger: false, version: {version: "23"},  resource: cpi-release}
        - {get: bosh-deployment,  trigger: false}
      - <<: *create-environment
      - <<: *prepare-director
        input_mapping:
          stemcell:     old-stemcell
          bosh-release: old-bosh-release
          cpi-release:  old-cpi-release
        params:
          <<: *prepare-director-params
          USE_REDIS:         true
      - do:
          - <<: *deploy-director
            input_mapping:
              stemcell:     old-stemcell
              bosh-release: old-bosh-release
              cpi-release:  old-cpi-release
          - task: create-deployment
            file: pipelines/shared/tasks/create-deployment.yml
            input_mapping:
              stemcell:        old-stemcell
            params:
              CERTIFICATION_OPS_FILE: pipelines/azure/assets/certification/ops.yml
              STEMCELL_NAME:          bosh-azure-hyperv-ubuntu-trusty-go_agent
          - <<: *prepare-director
          - task: test-upgrade
            file: pipelines/shared/tasks/test-upgrade.yml
            input_mapping:
              old-director-state: director-state
              new-director-config: director-config
            output_mapping:
              new-director-state: director-state
            params:
              DEPLOYMENT_NAME: certification
        ensure:
          do:
            - <<: *teardown
            - <<: *destroy-environment

  - name: certify-centos
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release, trigger: true, passed: [bats-centos]}
        - {get: cpi-release,  trigger: true, passed: [bats-centos]}
        - {get: stemcell,     trigger: true, passed: [bats-centos, test-upgrade], resource: centos-stemcell}
        - {get: pipelines,    trigger: false}
      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        params:
          CPI_RELEASE_NAME: bosh-azure-cpi
          STEMCELL_NAME:    bosh-azure-hyperv-centos-7-go_agent
      - {put: receipt, params: {file: certification/*-receipt.json}}

  - name: certify-ubuntu
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release, trigger: true, passed: [bats-ubuntu]}
        - {get: cpi-release,  trigger: true, passed: [bats-ubuntu]}
        - {get: stemcell,     trigger: true, passed: [bats-ubuntu, test-upgrade], resource: ubuntu-stemcell}
        - {get: pipelines,    trigger: false}
      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        params:
          CPI_RELEASE_NAME: bosh-azure-cpi
          STEMCELL_NAME:    bosh-azure-hyperv-ubuntu-trusty-go_agent
      - {put: receipt, params: {file: certification/*-receipt.json}}


resource_types:
- name: terraform_type
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

resources:
  - name: after-midnight
    type: time
    source:
      start: 12:00 AM -0700
      stop: 2:00 AM -0700
  - name: pipelines
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-cpi-certification
      branch: refactor
  - name: bosh-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment
      branch: master
  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh
  - name: bosh-cli
    type: s3
    source:
      regexp: bosh-cli-([0-9.]+)-linux-amd64
      bucket: bosh-cli-artifacts
      region_name: us-east-1
  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master
  - name: receipt
    type: s3
    source:
      access_key_id: {{certification__bucket_access_key}}
      secret_access_key: {{certification__bucket_secret_key}}
      bucket: {{certification__bucket}}
      regexp: .*-(\d+)-receipt\.json
      region_name: {{certification__bucket_region}}
  - name: cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-azure-cpi-release
  - name: ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-azure-hyperv-ubuntu-trusty-go_agent
  - name: old-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-azure-hyperv-ubuntu-trusty-go_agent
  - name: centos-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-azure-hyperv-centos-7-go_agent
  - name: environment
    type: terraform_type
    source:
      storage:
        access_key_id: {{terraform_bucket_access_key_id}}
        secret_access_key: {{terraform_bucket_secret_access_key}}
        bucket: {{terraform_bucket}}
        region_name: {{terraform_bucket_region}}
        bucket_path: {{terraform_bucket_path}}
      vars:
        azure_client_id: {{azure_client_id}}
        azure_client_secret: {{azure_client_secret}}
        azure_subscription_id: {{azure_subscription_id}}
        azure_tenant_id: {{azure_tenant_id}}
        location: West US
