azs:
- name: default
  cloud_properties: {}

vm_types:
- name: default
  cloud_properties: {}

networks:
- name: private
  type: manual
  subnets:
  - az: default
    range: ((internal_cidr))
    gateway: ((internal_gw))
    reserved: [((reserved_range))]
    cloud_properties: {}

compilation:
  workers: 1
  reuse_compilation_vms: true
  az: default
  vm_type: default
  network: private
