---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines
  - name: stemcell
  - name: deployment-manifest
  - name: bosh-cli
  - name: director-state

run:
  path: pipelines/azure/tasks/create-deployment.sh

params:
  RELEASE_NAME:       ""
  DEPLOYMENT_NAME:    ""
