---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines
  - name: bosh-release
  - name: cpi-release
  - name: stemcell
  - name: bosh-cli
  - name: environment
  - name: bosh-deployment

outputs:
  - name: director-config

run:
  path: pipelines/azure/tasks/prepare-director.sh

params:
  BOSH_CLIENT_SECRET:    ""
  AZURE_CLIENT_ID:       ""
  AZURE_CLIENT_SECRET:   ""
  AZURE_TENANT_ID:       ""
  AZURE_SUBSCRIPTION_ID: ""
  AZURE_ENVIRONMENT:     AzureCloud
  AZURE_DNS:             ""
  USE_REDIS:             false
