---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: bosh-cli
  - name: pipelines
  - name: environment

outputs:
  - name: deployment-manifest

run:
  path: pipelines/azure/tasks/prepare-deployment.sh

params:
  BOSH_CLIENT_SECRET:        ""
  RELEASE_NAME:              ""
  STEMCELL_NAME:             ""
  DEPLOYMENT_NAME:           ""
