---
groups:
  - name: certify-aws
    jobs:
      - bats-centos
      - bats-ubuntu
      - bats-xenial
      - test-stemcell
      - test-stemcell-xenial
      - end2end-us
      - test-upgrade
      - certify-centos
      - certify-ubuntu
      - certify-xenial

shared:
  - &prepare-director
    task: prepare-director
    file: pipelines/shared/tasks/prepare-director.yml
    params: &prepare-director-params
      INFRASTRUCTURE:     aws
      DIRECTOR_VARS_FILE: {{aws_director_vars_file}}
      OPTIONAL_OPS_FILE: |
        -o bosh-deployment/external-ip-with-registry-not-recommended.yml
        -o pipelines/shared/assets/ops/remove-provider-cert.yml

  - &prepare-director-xenial
    task: prepare-director
    file: pipelines/shared/tasks/prepare-director.yml
    params: &prepare-director-params
      INFRASTRUCTURE:     aws
      DIRECTOR_VARS_FILE: {{aws_director_vars_file}}
      OPTIONAL_OPS_FILE: |
        -o bosh-deployment/external-ip-with-registry-not-recommended.yml
        -o pipelines/shared/assets/ops/remove-provider-cert.yml

  - &deploy-director
    task: deploy-director
    file: pipelines/shared/tasks/deploy-director.yml

  - &run-bats
    task: run-bats
    file: pipelines/shared/tasks/run-bats.yml
    params: &run-bats-params
      INFRASTRUCTURE:     aws
      BAT_INFRASTRUCTURE: aws
      BAT_NETWORKING:     manual
      BAT_RSPEC_FLAGS:    "--tag ~multiple_manual_networks --tag ~root_partition"

  - &test-stemcell
    task: test-stemcell
    file: pipelines/shared/tasks/test-stemcell.yml
    params:
      BOSH_os_name: ubuntu-trusty
      package: ipv4director

  - &update-cloud-config
    task: update-cloud-config
    file: pipelines/shared/tasks/update-cloud-config.yml
    params: &update-cloud-config-params
      INFRASTRUCTURE: aws
      DIRECTOR_VARS_FILE: {{aws_director_vars_file}}

  - &run-end-2-end
    task: run-e2e
    file: bosh-cpi-src/ci/tasks/run-e2e.yml
    params:
      BOSH_AWS_KMS_KEY_ARN: {{aws_kms_key_arn}}

  - &create-environment
    put: environment
    params:
      delete_on_failure: true
      generate_random_name: true
      terraform_source: pipelines/aws/assets/terraform

  - &destroy-environment
    put: environment
    params:
      action: destroy
      env_name_file: environment/name
      terraform_source: pipelines/aws/assets/terraform
    get_params:
      action: destroy

  - &teardown
    task: teardown
    file: pipelines/shared/tasks/teardown.yml

jobs:
  - name: test-stemcell
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,    trigger: true}
        - {get: cpi-release,     trigger: true}
        - {get: stemcell,        trigger: true, resource: ubuntu-stemcell}
        - {get: after-midnight,  trigger: true}
        - {get: pipelines,       trigger: false}
        - {get: bosh-cli,        trigger: false}
        - {get: bats,            trigger: false}
        - {get: bosh-deployment, trigger: false}
        - {get: syslog-release,  trigger: false}
        - {get: os-conf-release, trigger: false}
        - {get: bosh-linux-stemcell-builder, trigger: false}
      - <<: *create-environment
      - do:
        - <<: *prepare-director
          params:
            <<: *prepare-director-params
            OPTIONAL_OPS_FILE: |
              -o pipelines/shared/assets/ops/remove-hm.yml
              -o bosh-deployment/external-ip-with-registry-not-recommended.yml
              -o pipelines/shared/assets/ops/remove-provider-cert.yml
        - do:
          - <<: *deploy-director
          - <<: *update-cloud-config
          - <<: *test-stemcell
          ensure:
            do:
              - <<: *teardown
        ensure:
          do:
            - <<: *destroy-environment

  - name: test-stemcell-xenial
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,    trigger: true}
        - {get: cpi-release,     trigger: true}
        - {get: stemcell,        trigger: true, resource: *xenial-stemcell}
        - {get: ubuntu-stemcell, trigger: true, resource: ubuntu-stemcell}
        - {get: after-midnight,  trigger: true}
        - {get: pipelines,       trigger: false}
        - {get: bosh-cli,        trigger: false}
        - {get: bats,            trigger: false}
        - {get: bosh-deployment, trigger: false}
        - {get: syslog-release,  trigger: false}
        - {get: os-conf-release, trigger: false}
        - {get: bosh-linux-stemcell-builder, trigger: false}
      - <<: *create-environment
      - do:
        - <<: *prepare-director
          input_mapping:
            stemcell: ubuntu-stemcell
          params:
            <<: *prepare-director-params
            OPTIONAL_OPS_FILE: |
              -o pipelines/shared/assets/ops/remove-hm.yml
              -o bosh-deployment/external-ip-with-registry-not-recommended.yml
              -o pipelines/shared/assets/ops/remove-provider-cert.yml
        - do:
          - <<: *deploy-director
            input_mapping:
              stemcell: ubuntu-stemcell
          - <<: *update-cloud-config
          - <<: *test-stemcell
          ensure:
            do:
              - <<: *teardown
        ensure:
          do:
            - <<: *destroy-environment

  - name: end2end-us
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,    trigger: true}
        - {get: cpi-release,     trigger: true}
        - {get: after-midnight,  trigger: true}
        - {get: centos-stemcell, trigger: false} # pass-thru to certification jobs
        - {get: *xenial-stemcell, trigger: false} # pass-thru to certification jobs
        - {get: pipelines,       trigger: false}
        - {get: bosh-cli,        trigger: false}
        - {get: bosh-deployment, trigger: false}
        - {get: bosh-cpi-src,    trigger: false}
        - get: heavy-stemcell
          resource: heavy-ubuntu-stemcell
          params:
            preserve_filename: true
        - get: stemcell
          resource: ubuntu-stemcell
          trigger: true
          params:
            preserve_filename: true
      - <<: *create-environment
      - do:
        - <<: *prepare-director
          params:
            <<: *prepare-director-params
            OPTIONAL_OPS_FILE:  |
              -o bosh-deployment/external-ip-with-registry-not-recommended.yml
              -o pipelines/shared/assets/ops/remove-provider-cert.yml
              -o pipelines/aws/assets/ops/iam-instance-profile-ops-file.yml
        - do:
            - <<: *deploy-director
            - <<: *run-end-2-end
          ensure:
            do:
              - <<: *teardown
        ensure:
          do:
            - <<: *destroy-environment

  - name: bats-centos
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,    trigger: true}
        - {get: cpi-release,     trigger: true}
        - {get: after-midnight,  trigger: true}
        - {get: pipelines,       trigger: false}
        - {get: bosh-cli,        trigger: false}
        - {get: bats,            trigger: false}
        - {get: bosh-deployment, trigger: false}
        - get: stemcell
          resource: centos-stemcell
          trigger: true
          params:
            preserve_filename: true
      - <<: *create-environment
      - do:
        - <<: *prepare-director
          params:
            <<: *prepare-director-params
            OPTIONAL_OPS_FILE:  |
              -o pipelines/shared/assets/ops/remove-hm.yml
              -o bosh-deployment/external-ip-with-registry-not-recommended.yml
              -o pipelines/shared/assets/ops/remove-provider-cert.yml
        - do:
          - <<: *deploy-director
          - <<: *run-bats
            params:
              <<: *run-bats-params
              STEMCELL_NAME: *centos-stemcell
          ensure:
            do:
              - <<: *teardown
        ensure:
          do:
            - <<: *destroy-environment

  - name: bats-ubuntu
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,    trigger: true}
        - {get: cpi-release,     trigger: true}
        - {get: after-midnight,  trigger: true}
        - {get: pipelines,       trigger: false}
        - {get: bosh-cli,        trigger: false}
        - {get: bats,            trigger: false}
        - {get: bosh-deployment, trigger: false}
        - get: stemcell
          resource: ubuntu-stemcell
          trigger: true
          params:
            preserve_filename: true
      - <<: *create-environment
      - do:
        - <<: *prepare-director
          params:
            <<: *prepare-director-params
            OPTIONAL_OPS_FILE:  |
              -o pipelines/shared/assets/ops/remove-hm.yml
              -o bosh-deployment/external-ip-with-registry-not-recommended.yml
              -o pipelines/shared/assets/ops/remove-provider-cert.yml
        - do:
          - <<: *deploy-director
          - <<: *run-bats
            params:
              <<: *run-bats-params
              STEMCELL_NAME: *ubuntu-stemcell
          ensure:
            do:
              - <<: *teardown
        ensure:
          do:
            - <<: *destroy-environment

  - name: bats-xenial
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,    trigger: true}
        - {get: cpi-release,     trigger: true}
        - {get: after-midnight,  trigger: true}
        - {get: pipelines,       trigger: false}
        - {get: bosh-cli,        trigger: false}
        - {get: bats,            trigger: false}
        - {get: bosh-deployment, trigger: false}
        - get: stemcell
          resource: *xenial-stemcell
          trigger: true
          params:
            preserve_filename: true
        - get: ubuntu-stemcell
          params:
            preserve_filename: true
      - <<: *create-environment
      - do:
        - <<: *prepare-director
          input_mapping:
            stemcell: ubuntu-stemcell
          params:
            <<: *prepare-director-params
            OPTIONAL_OPS_FILE:  |
              -o pipelines/shared/assets/ops/remove-hm.yml
              -o bosh-deployment/external-ip-with-registry-not-recommended.yml
              -o pipelines/shared/assets/ops/remove-provider-cert.yml
        - do:
          - <<: *deploy-director
            input_mapping:
              stemcell: ubuntu-stemcell
          - <<: *run-bats
            params:
              <<: *run-bats-params
              STEMCELL_NAME: *ubuntu-stemcell
          ensure:
            do:
              - <<: *teardown
        ensure:
          do:
            - <<: *destroy-environment

  - name: test-upgrade
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,     trigger: true}
        - {get: cpi-release,      trigger: true}
        - {get: after-midnight,   trigger: true}
        - {get: pipelines,        trigger: false}
        - {get: bosh-cli,         trigger: false}
        - {get: centos-stemcell,  trigger: false} # pass-through
        - {get: old-bosh-release, trigger: false, version: {version: {{old_bosh_release_version}}}, resource: bosh-release}
        - {get: old-cpi-release,  trigger: false, version: {version: "36"},  resource: cpi-release}
        - {get: bosh-deployment,  trigger: false}
        - get: stemcell
          resource: ubuntu-stemcell
          trigger: true
          params:
            preserve_filename: true
        - get: old-stemcell
          resource: old-ubuntu-stemcell
          trigger: false
          version:
            version: "3232.15"
          params:
            preserve_filename: true
      - <<: *create-environment
      - <<: *prepare-director
        input_mapping:
          stemcell:     old-stemcell
          bosh-release: old-bosh-release
          cpi-release:  old-cpi-release
        params:
          <<: *prepare-director-params
          OPTIONAL_OPS_FILE: |
            -o pipelines/shared/assets/ops/redis.yml
            -o bosh-deployment/external-ip-with-registry-not-recommended.yml
            -o pipelines/shared/assets/ops/remove-provider-cert.yml
      - do:
        - <<: *deploy-director
          input_mapping:
            stemcell:     old-stemcell
            bosh-release: old-bosh-release
            cpi-release:  old-cpi-release
        - <<: *update-cloud-config
        - task: create-deployment
          file: pipelines/shared/tasks/create-deployment.yml
          input_mapping:
            stemcell: old-stemcell
          params:
            INFRASTRUCTURE: aws
            STEMCELL_NAME:  bosh-aws-xen-hvm-ubuntu-trusty-go_agent
        - <<: *prepare-director
        - task: test-upgrade
          file: pipelines/shared/tasks/test-upgrade.yml
          input_mapping:
            old-director-state:  director-state
            new-director-config: director-config
          output_mapping:
            new-director-state:  director-state
        ensure:
          do:
            - <<: *teardown
            - <<: *destroy-environment

  - name: certify-centos
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release, trigger: true, passed: [bats-centos, end2end-us]}
        - {get: cpi-release,  trigger: true, passed: [bats-centos, end2end-us]}
        - {get: stemcell,     trigger: true, passed: [bats-centos, end2end-us, test-upgrade], resource: centos-stemcell}
        - {get: pipelines,    trigger: false}
      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        params:
          CPI_RELEASE_NAME: bosh-aws-cpi
          STEMCELL_NAME:    *centos-stemcell
      - {put: receipt, params: {file: certification/*-receipt.json}}

  - name: certify-ubuntu
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release, trigger: true, passed: [bats-ubuntu, end2end-us]}
        - {get: cpi-release,  trigger: true, passed: [bats-ubuntu, end2end-us]}
        - {get: stemcell,     trigger: true, passed: [bats-ubuntu, end2end-us, test-upgrade, test-stemcell], resource: ubuntu-stemcell}
        - {get: pipelines,    trigger: false}
      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        params:
          CPI_RELEASE_NAME: bosh-aws-cpi
          STEMCELL_NAME:    *ubuntu-stemcell
      - {put: receipt, params: {file: certification/*-receipt.json}}

  - name: certify-xenial
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release, trigger: true, passed: [bats-ubuntu, end2end-us]}
        - {get: cpi-release,  trigger: true, passed: [bats-ubuntu, end2end-us]}
        - {get: stemcell,     trigger: true, passed: [bats-xenial, end2end-us, test-stemcell-xenial], resource: *xenial-stemcell}
        - {get: pipelines,    trigger: false}
      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        params:
          CPI_RELEASE_NAME: bosh-aws-cpi
          STEMCELL_NAME:    *xenial-stemcell
      - {put: receipt, params: {file: certification/*-receipt.json}}

resource_types:
  - name: terraform_type
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource

resources:
  - name: after-midnight
    type: time
    source:
      start: 12:00 AM -0700
      stop: 2:00 AM -0700
  - name: bosh-cpi-src
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release.git
      branch: master
      paths:
        - ci/**
  - name: pipelines
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-cpi-certification
      branch: master
  - name: bosh-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment
      branch: master
  - name: cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-aws-cpi-release
  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh
  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: gocli-bats
  - name: ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: &ubuntu-stemcell bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  - name: heavy-ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: &heavy-ubuntu-stemcell bosh-aws-xen-ubuntu-trusty-go_agent
      force_regular: true
  - name: old-ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: *ubuntu-stemcell
  - name: centos-stemcell
    type: bosh-io-stemcell
    source:
      name: &centos-stemcell bosh-aws-xen-hvm-centos-7-go_agent
  - name: bosh-cli
    type: s3
    source:
      regexp: bosh-cli-([0-9.]+)-linux-amd64
      cloudfront_url: https://dulfnruy35dwq.cloudfront.net
      bucket: bosh-cli-artifacts
      region_name: us-east-1
  - name: receipt
    type: s3
    source:
      access_key_id: {{certification__bucket_access_key}}
      secret_access_key: {{certification__bucket_secret_key}}
      bucket: {{certification__bucket}}
      regexp: .*-(\d+)-receipt\.json
      region_name: us-east-1
  - name: environment
    type: terraform_type
    source:
      storage:
        access_key_id:     {{terraform_aws_access_key}}
        secret_access_key: {{terraform_aws_secret_key}}
        bucket:            {{terraform_bucket}}
        bucket_path:       terraform-state
      vars:
        access_key: {{AWS_ACCESS_KEY}}
        secret_key: {{AWS_SECRET_KEY}}
        region:     {{AWS_REGION_NAME}}
        public_key: {{PUBLIC_KEY}}
  - name: bosh-linux-stemcell-builder
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-linux-stemcell-builder
      branch: master
  - name: syslog-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/syslog-release
  - name: os-conf-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/os-conf-release
  - name: &xenial-stemcell bosh-aws-xen-hvm-ubuntu-xenial-go_agent
    type: s3
    source:
      bucket: {{xenial_candidate_stemcell_bucket}}
      regexp: aws/bosh-stemcell-(.+)-aws-xen-hvm-ubuntu-xenial-go_agent.tgz
      access_key_id: {{xenial_stemcell_aws_access_key}}
      secret_access_key: {{xenial_stemcell_aws_secret_key}}
