- type: replace
  path: /azs/name=default/cloud_properties
  value:
    zone: ((zone))

- type: replace
  path: /vm_types/name=default/cloud_properties
  value:
    machine_type: n1-standard-2
    root_disk_size_gb: 20
    root_disk_type: pd-ssd

- type: replace
  path: /networks/name=private/subnets/0/cloud_properties
  value:
    network_name: ((network))
    subnetwork_name: ((subnetwork))
