---
groups:
  - name: certify-vsphere
    jobs:
      - bats-centos
      - bats-ubuntu
      - test-upgrade
      - certify-centos
      - certify-ubuntu

shared:
  - &prepare-director
    task: prepare-director
    tags: [vsphere-v6.0]
    file: pipelines/shared/tasks/prepare-director.yml
    params: &prepare-director-params
      INFRASTRUCTURE:     vsphere
      DIRECTOR_VARS_FILE: {{vsphere_director_vars_file}}
      OPTIONAL_OPS_FILE:  |
        -o bosh-deployment/vsphere/resource-pool.yml

  - &deploy-director
    task: deploy-director
    tags: [vsphere-v6.0]
    file: pipelines/shared/tasks/deploy-director.yml
    params:
      NETWORK_NAME: default

  - &run-bats
    task: run-bats
    tags: [vsphere-v6.0]
    file: pipelines/shared/tasks/run-bats.yml
    params: &run-bats-params
      INFRASTRUCTURE:     vsphere
      BAT_INFRASTRUCTURE: vsphere
      BAT_NETWORKING:     manual
      BAT_RSPEC_FLAGS:    "--tag ~vip_networking --tag ~dynamic_networking --tag ~root_partition --tag ~raw_ephemeral_storage"

  - &teardown
    task: teardown
    tags: [vsphere-v6.0]
    file: pipelines/shared/tasks/teardown.yml
    params:
      DEPLOYMENT_NAME: certification

jobs:
  - name: bats-centos
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,    tags: [vsphere-v6.0], trigger: true}
        - {get: cpi-release,     tags: [vsphere-v6.0], trigger: true}
        - {get: stemcell,        tags: [vsphere-v6.0], trigger: true, resource: centos-stemcell}
        - {get: after-midnight,  tags: [vsphere-v6.0], trigger: true}
        - {get: pipelines,       tags: [vsphere-v6.0], trigger: false}
        - {get: bosh-cli,        tags: [vsphere-v6.0], trigger: false}
        - {get: bats,            tags: [vsphere-v6.0], trigger: false}
        - {get: bosh-deployment, tags: [vsphere-v6.0], trigger: false}
      - {put: environment, tags: [vsphere-v6.0], params: {acquire: true}}
      - <<: *prepare-director
      - do:
          - <<: *deploy-director
          - <<: *run-bats
            params:
              <<: *run-bats-params
              STEMCELL_NAME: bosh-vsphere-esxi-centos-7-go_agent
        ensure:
          do:
            - <<: *teardown
            - {put: environment, tags: [vsphere-v6.0], params: {release: environment}}

  - name: bats-ubuntu
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,    tags: [vsphere-v6.0], trigger: true}
        - {get: cpi-release,     tags: [vsphere-v6.0], trigger: true}
        - {get: stemcell,        tags: [vsphere-v6.0], trigger: true, resource: ubuntu-stemcell}
        - {get: after-midnight,  tags: [vsphere-v6.0], trigger: true}
        - {get: pipelines,       tags: [vsphere-v6.0], trigger: false}
        - {get: bosh-cli,        tags: [vsphere-v6.0], trigger: false}
        - {get: bats,            tags: [vsphere-v6.0], trigger: false}
        - {get: bosh-deployment, tags: [vsphere-v6.0], trigger: false}
      - {put: environment, tags: [vsphere-v6.0], params: {acquire: true}}
      - <<: *prepare-director
      - do:
          - <<: *deploy-director
          - <<: *run-bats
            params:
              <<: *run-bats-params
              STEMCELL_NAME: bosh-vsphere-esxi-ubuntu-trusty-go_agent
        ensure:
          do:
            - <<: *teardown
            - {put: environment, tags: [vsphere-v6.0], params: {release: environment}}

  - name: test-upgrade
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,     tags: [vsphere-v6.0], trigger: true}
        - {get: cpi-release,      tags: [vsphere-v6.0], trigger: true}
        - {get: stemcell,         tags: [vsphere-v6.0], trigger: true, resource: ubuntu-stemcell}
        - {get: after-midnight,   tags: [vsphere-v6.0], trigger: true}
        - {get: pipelines,        tags: [vsphere-v6.0], trigger: false}
        - {get: bosh-cli,         tags: [vsphere-v6.0], trigger: false}
        - {get: centos-stemcell,  tags: [vsphere-v6.0], trigger: false} # pass-through
        - {get: old-stemcell,     tags: [vsphere-v6.0], trigger: false}
        - {get: old-bosh-release, tags: [vsphere-v6.0], trigger: false, version: {version: "255.4"}, resource: bosh-release}
        - {get: old-cpi-release,  tags: [vsphere-v6.0], trigger: false, version: {version: "14"},  resource: cpi-release}
        - {get: bosh-deployment,  tags: [vsphere-v6.0], trigger: false}
      - {put: environment, tags: [vsphere-v6.0], params: {acquire: true}}
      - <<: *prepare-director
        input_mapping:
          stemcell:     old-stemcell
          bosh-release: old-bosh-release
          cpi-release:  old-cpi-release
        params:
          <<: *prepare-director-params
          USE_REDIS:         true
      - do:
          - <<: *deploy-director
            input_mapping:
              stemcell:     old-stemcell
              bosh-release: old-bosh-release
              cpi-release:  old-cpi-release
          - task: create-deployment
            tags: [vsphere-v6.0]
            file: pipelines/shared/tasks/create-deployment.yml
            input_mapping:
              stemcell:                  old-stemcell
            params:
              BOSH_VSPHERE_VCENTER_VLAN: {{VCENTER_VLAN}}
              INFRASTRUCTURE:            vsphere
              STEMCELL_NAME:             bosh-vsphere-esxi-ubuntu-trusty-go_agent
          - <<: *prepare-director
          - task: test-upgrade
            tags: [vsphere-v6.0]
            file: pipelines/shared/tasks/test-upgrade.yml
            input_mapping:
              old-director-state: director-state
              new-director-config: director-config
            output_mapping:
              new-director-state: director-state
            params:
              DEPLOYMENT_NAME:        certification
        ensure:
          do:
            - <<: *teardown
            - {put: environment, tags: [vsphere-v6.0], params: {release: environment}}

  - name: certify-centos
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release, tags: [vsphere-v6.0], trigger: true, passed: [bats-centos]}
        - {get: cpi-release,  tags: [vsphere-v6.0], trigger: true, passed: [bats-centos]}
        - {get: stemcell,     tags: [vsphere-v6.0], trigger: true, passed: [bats-centos, test-upgrade], resource: centos-stemcell}
        - {get: pipelines,    tags: [vsphere-v6.0], trigger: false}
      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        tags: [vsphere-v6.0]
        params:
          CPI_RELEASE_NAME: bosh-vsphere-cpi
          STEMCELL_NAME:    bosh-vsphere-esxi-centos-7-go_agent
      - {put: receipt, tags: [vsphere-v6.0], params: {file: certification/*-receipt.json}}

  - name: certify-ubuntu
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release, tags: [vsphere-v6.0], trigger: true, passed: [bats-ubuntu]}
        - {get: cpi-release,  tags: [vsphere-v6.0], trigger: true, passed: [bats-ubuntu]}
        - {get: stemcell,     tags: [vsphere-v6.0], trigger: true, passed: [bats-ubuntu, test-upgrade], resource: ubuntu-stemcell}
        - {get: pipelines,    tags: [vsphere-v6.0], trigger: false}
      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        tags: [vsphere-v6.0]
        params:
          CPI_RELEASE_NAME: bosh-vsphere-cpi
          STEMCELL_NAME:    bosh-vsphere-esxi-ubuntu-trusty-go_agent
      - {put: receipt, tags: [vsphere-v6.0], params: {file: certification/*-receipt.json}}

resources:
  - name: after-midnight
    type: time
    source:
      start: 12:00 AM -0700
      stop: 2:00 AM -0700
  - name: pipelines
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-cpi-certification
      branch: gcp-certification
  - name: bosh-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment
      branch: master
  - name: cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-vsphere-cpi-release
  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh
  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: gcp-certification-2
  - name: centos-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-centos-7-go_agent
  - name: ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
  - name: old-stemcell
    type: s3
    source:
      bucket: bosh-cpi-certification-fixtures
      regexp: bosh-stemcell-(3213)-vsphere-esxi-ubuntu-trusty-go_agent.tgz
      region_name: us-east-1
  - name: bosh-cli
    type: s3
    source:
      regexp: bosh-cli-([0-9.]+)-linux-amd64
      bucket: bosh-cli-artifacts
      region_name: us-east-1
  - name: receipt
    type: s3
    source:
      access_key_id: {{certification__bucket_access_key}}
      secret_access_key: {{certification__bucket_secret_key}}
      bucket: {{certification__bucket}}
      regexp: .*-(\d+)-receipt\.json
      region_name: us-east-1
  - name: environment
    type: pool
    source:
      pool: vsphere-6.0
      uri: git@github.com:cloudfoundry/bosh-cpi-environments.git
      branch: master
      private_key: {{github_deployment_key__bosh-cpi-environments}}
