---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines

outputs:
  - name: environment

run:
  path: pipelines/aws/tasks/prepare-environment.sh

params:
  AWS_ACCESS_KEY_ID:     ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION:    ""
  AWS_STACK_NAME:        ""
  PUBLIC_KEY_NAME:       ""
