---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines
  - name: director-state
  - name: deployment-manifest
  - name: stemcell
  - name: bosh-cli

run:
  path: pipelines/shared/tasks/create-deployment.sh

params:
  DEPLOYMENT_NAME:    ""
  RELEASE_NAME:       ""
