---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines
  - name: environment
  - name: director-state
  - name: stemcell
  - name: bosh-cli

run:
  path: pipelines/shared/tasks/create-deployment.sh

params:
  BOSH_VSPHERE_VCENTER_VLAN: ""
  INFRASTRUCTURE:            ""
  DEPLOYMENT_NAME:           certification
  RELEASE_NAME:              certification
  STEMCELL_NAME:             ""
