---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines
  - name: environment
  - name: bats
  - name: director-state
  - name: bosh-cli

outputs:
  - name: bats-config

run:
  path: pipelines/shared/tasks/prepare-bats.sh

params:
  BAT_VCAP_PASSWORD:  ""
  BOSH_CLIENT_SECRET: ""
  STEMCELL_NAME:      ""
  INCLUDE_FILE:       ""
  BATS_SPEC:          ""
