- type: replace
  path: /vm_types/name=default/cloud_properties
  value:
    cpu: 2
    ram: 1024
    disk: 10240

- type: replace
  path: /networks/name=private/subnets/0
  value:
    az: default
    range: ((network1.vCenterCIDR))
    gateway: ((network1.vCenterGateway))
    reserved: ((network1.reservedRange))
    static: ((network1.staticRange))
    dns: ((DNS))
    cloud_properties:
      name: ((network_name))
