- type: replace
  path: /azs/name=default/cloud_properties
  value:
    availability_zone: ((az))

- type: replace
  path: /vm_types/name=default/cloud_properties
  value:
    instance_type: t2.medium

- type: replace
  path: /networks/name=private/subnets/0/cloud_properties
  value:
    subnet: ((subnet_id))
